### PR TITLE
Add Status Bar UI for Playing Codio

### PR DESCRIPTION
**Pull request by rbrisita**
Adding a status bar item to write progress to when codio is playing and allow stop on click.

# Sneak Peek
codio_status-bar

# Changes
- Removed some information messages pertaining to playing, pausing, and stopping a codio.
- Added a status bar item to show playing progress.
- Added player and command palette stop functionality.
- Added click on status bar to stop currently playing codio.
- Removed showPlayerProgressBar method from messages.

### CODE REVIEW

**Comment by rbrisita** [comment]
Rebased with master.

**Comment by bogobogo** [comment]
This is very cool.

**Comment by bogobogo** [comment]
@rbrisita  I am afraid that new Codio users won't know how to stop a Codio. Also, some users hide the bottom bar. 

I suggest showing the previous progress by default, but enabling the users to change it through the settings

**Comment by rbrisita** [comment]
Considering the audience and that VS Code and other extensions use the status bar for primary information I believe your concern is unfounded. Using gifs or the 'Welcome!' codio to show proper usage would suffice.

**Comment by rbrisita** [comment]
I will be working on my own branch from now on. I created tags to clearly state when it branched. I will change the name to 'Codio-SUI' and the README.md to clearly state the differences. Thank you for your time on this.

**Pull request closed without merging**
