### PR TITLE
Windows Recording Bug Fix

### PR DESCRIPTION
**Pull request by rbrisita**
The current version in Windows 10 cuts the audio portion of the codio by as much as ~15 seconds because of the approach to ending the `ffmpeg` child process. This PR introduces better handling of playing and recording audio clips on Windows 10. This approach might also work on OS X and *nix systems but unfortunately I do not have access to test on those platforms.

* The child process will now `autoexit` when playing. This might be possible on recording too but will be tested at a later date.
* A quit command is now sent to `ffmpeg` when `stopAudioProcess` is called and Windows is detected.
* The events fired from the above command handles exiting the process correctly to result in a full audio recording of the codio in Windows.

Please let me know your thoughts.

### CODE REVIEW

**Comment by bogobogo** [comment]
@rbrisita  Thanks for the PR! Taking a look. I want to make sure it still works on macOS as expected

**Comment by rbrisita** [comment]
Any update on this? Please let me know how I can be of help.

**Comment by bogobogo** [comment]
@rbrisita going over it today, sorry for the delay!

**Comment by bogobogo** [comment]
@rbrisita verified that works on mac, merged

**Pull request merged**
